version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - auth-service
      - conversation-service
      - voice-service
    networks:
      - medical-chatbot-network

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - medical-chatbot-network

  conversation-service:
    build: ./conversation-service
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - medical-chatbot-network

  voice-service:
    build: ./voice-service
    ports:
      - "8003:8003"
    env_file:
      - .env
    networks:
      - medical-chatbot-network

networks:
  medical-chatbot-network:
    driver: bridge
