app = "medical-chatbot"
primary_region = "iad"  # Change to your preferred region

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services.concurrency]
  hard_limit = 25
  soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # Adjust based on your needs

[env]
  PORT = "8000"
  # Environment variables will be set through fly secrets
