# fly.toml app configuration file generated for medbot-agent on 2025-05-26T00:28:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medbot-agent'
primary_region = 'sin'
kill_timeout = '5m0s'

[build]
  dockerfile = 'Dockerfile.worker'
  ignorefile = '.dockerignore'

[deploy]
  strategy = 'bluegreen'

[env]
  PYTHONUNBUFFERED = '1'

[checks]
  [checks.healthcheck]
    port = 8081
    type = 'tcp'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
